N1:
  - N1
  - N2
  - N3
  - N4
N9:
  - N9
  - MSG
PO1:
  - PO1
  - PID
  - SCH
CTT:
  - CTT
AK2:
  - AK2
  - AK3
  - AK4
  - AK5
AK3:
  - AK3
  - AK4
HL:
  - HL
  - LIN
  - SN1
  - SLN
  - PRF
  - PO4
  - PID
  - TD1
  - TD5
  - TD3
  - REF
  - MAN
  - DTM
  - FOB
  - PAL
IT1:
  - IT1
  - CTP
PID:
  - PID
  - REF
SAC:
  - SAC
SLN:
  - SLN
  - PID
ACK:
  - ACK
  - MAN